version: '3'
services:
  office:
    # image: 507441615853.dkr.ecr.eu-north-1.amazonaws.com/eningo-dig-portal:latest # TODO: Create the ECR repo
    build:
      dockerfile: Dockerfile
      context: .

    ports:
      - '3000:3000'
    env_file: ./.env    

    deploy:
      replicas: 1
      restart_policy:
        condition: always
        window: 60s
